//Last Updated: 8/28/2026
//Author: .eskie

let target = Array.from(game.user.targets)[0]

new Sequence()

  .effect()
  .file("eskie.casting.physical.03.side.one_shot.purple")
  .attachTo(token)
  .rotateTowards(target)
  .scaleToObject(1)
  .zIndex(2)
  .filter("ColorMatrix", { hue: 35, brightness:1})
  .waitUntilFinished(-750)

  .effect()
  .file("eskie.attack.ranged.arrow.01.physical.medium.purple.slow")
  .atLocation(token)
  .stretchTo(target, {attachTo: false})
  .zIndex(2)
  .filter("ColorMatrix", { hue: 35, brightness:1})
  .waitUntilFinished(-750)

  .effect()
  .copySprite(target)
  .attachTo(target)
  .scaleToObject(1,{considerTokenScale:true})
  .loopProperty("sprite", "position.x", { from: -0.05, to: 0.05, duration: 50, pingPong: true, gridUnits: true})
  .opacity(0.5)
  .duration(1000)
  .fadeOut(250)

  .effect()
  .file("jb2a.impact_themed.heart.02.pink")
  .attachTo(target)
  .scaleToObject(1.25)
  .zIndex(1)

  .effect()
  .file("eskie.damage.psychic.01.pink")
  .attachTo(target, {bindAlpha: false, bindVisibility: false})
  .scaleToObject(1.5, {considerTokenScale: true})
  .zIndex(1)

  .effect()
  .copySprite(target)
  .attachTo(target)
  .scaleToObject(1, {considerTokenScale: true})
  .fadeIn(500)
  .duration(8750)
  .fadeOut(1000)
  .opacity(0.75)
  .rotate(0)
  .belowTokens()
  .filter("Glow", { color: 0xfd5dbb, distance: 10, outerStrength:4, innerStrength: 0 })
  .filter("ColorMatrix", { saturate:-0.2, brightness:1.2 })

  .effect()
  .file("jb2a.template_circle.symbol.out_flow.heart.pink")
  .attachTo(target)
  .scaleToObject(1.75, {considerTokenScale: true})
  .fadeIn(500)
  .duration(8750)
  .belowTokens()
  .fadeOut(1000)

  .effect()
  .file("jb2a.extras.tmfx.border.circle.outpulse.01.fast")
  .attachTo(target)
  .scaleToObject(0.95, {considerTokenScale: true})
  .fadeIn(500)
  .duration(8750)
  .fadeOut(1000)
  .playbackRate(1.25)
  .tint("#fd5dbb")
  .zIndex(1)

.play()