//Last Updated: 8/28/2026
//Author: .eskie

let target = Array.from(game.user.targets)[0]

  new Sequence()

    .effect()
    .file("eskie.casting.physical.03.side.one_shot.purple")
    .attachTo(token)
    .rotateTowards(target)
    .scaleToObject(1)
    .zIndex(2)
    .filter("ColorMatrix", { hue: -35, brightness:0.2})
    .waitUntilFinished(-750)

    .effect()
    .file("eskie.attack.ranged.arrow.01.physical.medium.purpleblack.slow")
    .atLocation(token)
    .stretchTo(target)
    .zIndex(2)
    .filter("ColorMatrix", { hue: -35, brightness:0.2})
    .waitUntilFinished(-750)

    .effect()
    .copySprite(target)
    .attachTo(target)
    .scaleToObject(1,{considerTokenScale:true})
    .loopProperty("sprite", "position.x", { from: -0.05, to: 0.05, duration: 50, pingPong: true, gridUnits: true})
    .opacity(0.5)
    .duration(1000)
    .fadeOut(250)

    .effect()
    .file("eskie.damage.psychic.01.darkpurple")
    .attachTo(target, {bindAlpha: false, bindVisibility: false})
    .scaleToObject(1.5, {considerTokenScale: true})
    .filter("ColorMatrix", { saturate:-1})  
    .zIndex(1)


    .effect()
    .file("jb2a.smoke.puff.centered.dark_black")
    .atLocation(target)
    .scaleToObject(1.65, {considerTokenScale: true})
    .randomRotation()
    .repeats(3, 250, 250)
    .belowTokens()
    .playbackRate(1.2)

    .zIndex(2)

    .effect()
    .copySprite(target)
    .attachTo(target)
    .scaleToObject(1, {considerTokenScale:true})
    .rotate(0)
    .fadeIn(2000)
    .fadeOut(1500)
    .duration(4500)
    .filter("ColorMatrix", { saturate:-1, brightness:0.75 })

    .effect()
    .delay(1000)
    .file("jb2a.sleep.cloud.02.dark_purple")
    .attachTo(target, {offset:{y:-0}, gridUnits:true, local: true})
    .scaleToObject(1.5, {considerTokenScale: true})
    .spriteScale({x:1, y:1})
    .fadeIn(1500)
    .opacity(1)
    .filter("ColorMatrix", { saturate:-1, brightness:0 })
    .loopProperty("alphaFilter", "alpha", { from: -0.2, to: 0, duration: 2500, pingPong: true})
    .belowTokens()
    .persist()

    .effect()
    .delay(1000)
    .file("jb2a.extras.tmfx.inflow.circle.02")
    .attachTo(target, {offset:{y:-0}, gridUnits:true, local: true})
    .scaleToObject(1.1, {considerTokenScale: true})
    .spriteScale({x:1, y:1})
    .fadeIn(1500)
    .opacity(1)
    .filter("ColorMatrix", { saturate:-1, brightness:0 })
    .loopProperty("alphaFilter", "alpha", { from: -0.2, to: 0, duration: 2500, pingPong: true})
    .mask()
    .persist()

    .effect()
    .file("eskie.symbol.eye.01.purple")
    .attachTo(target, {offset:{y:-0}, gridUnits:true, local: true})
    .scaleToObject(0.45, {considerTokenScale: true})
    .fadeIn(1500)
    .opacity(0.8)
    .filter("ColorMatrix", { saturate:-1 })
    .persist()
    .zIndex(1)

  .play()